import "./globals.css";
import { Inter } from 'next/font/google';
import Header from "./Components/Header";
import Home from "./Components/Home";
import SecondContainer from "./Components/SecondContainer";
import ThirdContainer from "./Components/ThirdContainer";
import FourthContainer from "./Components/FourthContainer";
import FifthContainer from "./Components/FifthContainer";
import Footer from "./Components/footer";
import Keela from "./Components/Keela";
const inter = Inter({
  weight: ['400', '700','900'],  // Specify the font weights
  subsets: ['cyrillic'],      // Specify the subsets
});

export const metadata = {
  title: "Interior Design Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en smooth-scroll">
      <body className={ `${inter.className} bg-olivegreen text-white`}>
        <Header />
        <Home />
        <SecondContainer />
        <ThirdContainer />
        <FourthContainer />
        <FifthContainer />
        <Keela />
        {children}
      </body>
    </html>
  );
}
